import sequelize from "./db.js";

import Client from "./models/Client.js";
import Product from "./models/Product.js";
import Order from "./models/Order.js";
import OrderDetails from "./models/OrderDetails.js";
import Payment from "./models/Payment.js";

const Client = [
    { surname: "Петренко", name: "Іван" },
    { surname: "Коваленко", name: "Марія" },
    { surname: "Шевченко", name: "Олег" },
    { surname: "Мельник", name: "Наталія" },
    { surname: "Бондаренко", name: "Андрій" },
    { surname: "Гриценко", name: "Софія" },
    { surname: "Савченко", name: "Дмитро" },
    { surname: "Остапенко", name: "Христина" },
    { surname: "Кириленко", name: "Владислав" },
    { surname: "Гаврилюк", name: "Юлія" },
    { surname: "Ткаченко", name: "Михайло" },
    { surname: "Романенко", name: "Алла" },
    { surname: "Марущак", name: "Тетяна" },
    { surname: "Руденко", name: "Степан" },
    { surname: "Демчук", name: "Оксана" },
    { surname: "Павленко", name: "Ярослав" },
    { surname: "Сидоренко", name: "Валентина" },
    { surname: "Мазур", name: "Богдан" },
    { surname: "Корнієнко", name: "Дарина" },
    { surname: "Семенюк", name: "Арсен" },
    { surname: "Жук", name: "Олена" },
    { surname: "Дмитренко", name: "Віталій" },
    { surname: "Білан", name: "Інна" },
    { surname: "Кравець", name: "Руслан" },
    { surname: "Таран", name: "Маргарита" },
    { surname: "Юрченко", name: "Олександр" },
    { surname: "Кузьменко", name: "Марина" },
    { surname: "Іванців", name: "Антон" },
    { surname: "Войтенко", name: "Людмила" },
    { surname: "Стецюк", name: "Володимир" },
    { surname: "Бабенко", name: "Орися" },
    { surname: "Кириченко", name: "Тимофій" },
    { surname: "Соколенко", name: "Вероніка" },
    { surname: "Лисак", name: "Павло" },
    { surname: "Пастушенко", name: "Євгенія" },
    { surname: "Мироненко", name: "Олексій" },
    { surname: "Гордійчук", name: "Катерина" },
    { surname: "Захарченко", name: "Данило" },
    { surname: "Поляк", name: "Ілона" },
    { surname: "Олійник", name: "Сергій" },
    { surname: "Яценко", name: "Аліса" },
    { surname: "Левченко", name: "Кирило" },
    { surname: "Сич", name: "Олексій" },
    { surname: "Мартинюк", name: "Єва" },
    { surname: "Костенко", name: "Віолетта" },
    { surname: "Мірошниченко", name: "Роман" },
    { surname: "Рибак", name: "Анна" },
    { surname: "Пащенко", name: "Матвій" },
    { surname: "Луценко", name: "Галина" },
    { surname: "Терещенко", name: "Юрій" },
    { surname: "Костишин", name: "Аріна" },
    { surname: "Зозуля", name: "Омелян" },
    { surname: "Василенко", name: "Лілія" },
    { surname: "Бурак", name: "Святослав" },
    { surname: "Гуменюк", name: "Марта" },
    { surname: "Власенко", name: "Ростислав" },
    { surname: "Ільчук", name: "Емілія" },
    { surname: "Паламарчук", name: "Максим" },
    { surname: "Гончаренко", name: "Каріна" },
    { surname: "Рибчинський", name: "Ігор" },
    { surname: "Супрун", name: "Лука" },
    { surname: "Кушнір", name: "Леся" },
    { surname: "Бобик", name: "Марко" },
    { surname: "Остафійчук", name: "Олеся" },
    { surname: "Тимченко", name: "Федір" },
    { surname: "Жеребецька", name: "Дарина" },
    { surname: "Петрук", name: "Юстина" },
    { surname: "Симоненко", name: "Давид" },
    { surname: "Галенко", name: "Любов" },
    { surname: "Погорілий", name: "Іван" },
    { surname: "Лисогор", name: "Георгій" },
    { surname: "Климчук", name: "Соломія" },
    { surname: "Ісаєнко", name: "Вадим" },
    { surname: "Борисенко", name: "Аліна" },
    { surname: "Кравченко", name: "Денис" },
    { surname: "Мороз", name: "Лариса" },
    { surname: "Гумен", name: "Оксана" },
    { surname: "Скрипник", name: "Ян" },
    { surname: "Ярошенко", name: "Дарина" },
    { surname: "Підберезняк", name: "Єлизавета" },
    { surname: "Сташенко", name: "Гліб" },
    { surname: "Олійничук", name: "Віра" },
    { surname: "Білик", name: "Радомир" },
    { surname: "Шпак", name: "Емілія" },
    { surname: "Кірєєв", name: "Даніель" },
    { surname: "Сірош", name: "Ангеліна" },
    { surname: "Кушнір", name: "Ірина" },
    { surname: "Галюк", name: "Сергій" },
    { surname: "Наконечний", name: "Олександр" },
    { surname: "Козак", name: "Тимур" },
    { surname: "Ткачук", name: "Вікторія" },
    { surname: "Огієнко", name: "Дмитро" },
    { surname: "Климчук", name: "Вікторія" },
    { surname: "Шпак", name: "Тарас" },
    { surname: "Ігнатов", name: "Ярослав" },
    { surname: "Парубочий", name: "Олександр" },
    { surname: "Ляш", name: "Олексадра" },
    { surname: "Ціолковський", name: "Олег" },
    { surname: "Дудич", name: "Андріана" },
    { surname: "Костюк", name: "Віталіна" },
    { surname: "Тарасовський", name: "Андрій" },  
  ];    
  
const Product = [
    { category: "Ноутбуки", name: "HP ProBook 450 G8", price: 32000 },
    { category: "Ноутбуки", name: "Lenovo ThinkPad L14", price: 38000 },
    { category: "Ноутбуки", name: "Dell Inspiron 5515", price: 35000 },
    { category: "Ноутбуки", name: "Asus VivoBook 15 OLED", price: 29000 },
    { category: "Ноутбуки", name: "Acer Aspire 7 A715", price: 31000 },
    { category: "Ноутбуки", name: "Apple MacBook Air M1", price: 45000 },
    { category: "Ноутбуки", name: "Apple MacBook Pro 14 M2", price: 82000 },
    { category: "Ноутбуки", name: "MSI Modern 15 B12", price: 36000 },
    { category: "Ноутбуки", name: "HP Pavilion 15", price: 28000 },
    { category: "Ноутбуки", name: "Lenovo IdeaPad 5", price: 26000 },
    { category: "Ноутбуки", name: "Dell XPS 13 9310", price: 90000 },
    { category: "Ноутбуки", name: "Asus TUF Gaming F15", price: 56000 },
    { category: "Ноутбуки", name: "Acer Nitro 5 AN515", price: 54000 },
    { category: "Ноутбуки", name: "Huawei MateBook D16", price: 34000 },
    { category: "Ноутбуки", name: "Samsung Galaxy Book3", price: 37000 },
    { category: "Ноутбуки", name: "Lenovo Yoga Slim 7", price: 43000 },
    { category: "Ноутбуки", name: "HP Envy 13", price: 42000 },
    { category: "Ноутбуки", name: "Dell G15 Ryzen Edition", price: 60000 },
    { category: "Ноутбуки", name: "Asus ZenBook 14", price: 46000 },
    { category: "Ноутбуки", name: "Acer Swift 3", price: 32000 },

    { category: "Планшети", name: "Apple iPad 10", price: 20000 },
    { category: "Планшети", name: "Apple iPad Air 5", price: 28000 },
    { category: "Планшети", name: "Apple iPad Pro 11 M2", price: 45000 },
    { category: "Планшети", name: "Samsung Galaxy Tab A8", price: 12000 },
    { category: "Планшети", name: "Samsung Galaxy Tab S7 FE", price: 20000 },
    { category: "Планшети", name: "Lenovo Tab M10 Plus", price: 11000 },
    { category: "Планшети", name: "Lenovo Yoga Tab 11", price: 17000 },
    { category: "Планшети", name: "Xiaomi Pad 6", price: 22000 },
    { category: "Планшети", name: "Huawei MatePad 11", price: 23000 },
    { category: "Планшети", name: "Huawei MatePad SE", price: 13000 },
    { category: "Планшети", name: "Realme Pad Mini", price: 9000 },
    { category: "Планшети", name: "Nokia T21", price: 11500 },
    { category: "Планшети", name: "Samsung Galaxy Tab S9", price: 48000 },
    { category: "Планшети", name: "Apple iPad mini 6", price: 29000 },
    { category: "Планшети", name: "Lenovo Tab P11 Pro", price: 18500 },

    { category: "Комп'ютери", name: "ПК Ryzen 5 / RTX 3060", price: 56000 },
    { category: "Комп'ютери", name: "Офісний ПК i3 / 8GB / SSD 256", price: 18000 },
    { category: "Комп'ютери", name: "ПК i7 / 32GB / RTX 4070", price: 99000 },
    { category: "Комп'ютери", name: "Intel NUC Mini PC", price: 24000 },
    { category: "Комп'ютери", name: "ПК бюджетний i3 / 16GB", price: 21000 },
    { category: "Комп'ютери", name: "ПК відеомонтаж Ryzen 7 / 32GB", price: 77000 },
    { category: "Комп'ютери", name: "ПК i9 / RTX 4090 Ultra", price: 165000 },
    { category: "Комп'ютери", name: "Домашній ПК базовий", price: 15000 },
    { category: "Комп'ютери", name: "ПК для 1С i3 / SSD 512GB", price: 18500 },
    { category: "Комп'ютери", name: "ПК CAD / AutoCAD i7", price: 90000 },
    { category: "Комп'ютери", name: "ПК Ryzen 3 / Vega 8", price: 19000 },
    { category: "Комп'ютери", name: "ПК i5 / 16GB / SSD 512GB", price: 31000 },
    { category: "Комп'ютери", name: "ПК з монітором 24''", price: 29000 },
    { category: "Комп'ютери", name: "ПК Ryzen 5 для стріму", price: 62000 },
    { category: "Комп'ютери", name: "ПК офісний mini-tower", price: 20000 },
    { category: "Комп'ютери", name: "ПК Linux workstation", price: 35000 },
    { category: "Комп'ютери", name: "ПК Intel i5 + GTX 1660", price: 41000 },
    { category: "Комп'ютери", name: "ПК офісний slim", price: 19500 },
    { category: "Комп'ютери", name: "ПК для школи i3 / SSD", price: 25000 },
    { category: "Комп'ютери", name: "ПК Dual Monitor Pro", price: 47000 },

    { category: "Смарт-годинники", name: "Apple Watch Series 8", price: 19000 },
    { category: "Смарт-годинники", name: "Apple Watch SE 2023", price: 15000 },
    { category: "Смарт-годинники", name: "Apple Watch Ultra 2", price: 32000 },
    { category: "Смарт-годинники", name: "Samsung Galaxy Watch 6", price: 17000 },
    { category: "Смарт-годинники", name: "Samsung Galaxy Watch 5 Pro", price: 20000 },
    { category: "Смарт-годинники", name: "Xiaomi Watch S3", price: 10000 },
    { category: "Смарт-годинники", name: "Xiaomi Mi Band 8 Pro", price: 2500 },
    { category: "Смарт-годинники", name: "Huawei Watch GT 4", price: 13000 },
    { category: "Смарт-годинники", name: "Huawei Band 8", price: 2800 },
    { category: "Смарт-годинники", name: "Garmin Fenix 7X", price: 38000 },
    { category: "Смарт-годинники", name: "Garmin Forerunner 265", price: 21000 },
    { category: "Смарт-годинники", name: "Amazfit GTR 4", price: 8500 },
    { category: "Смарт-годинники", name: "Amazfit Bip 4", price: 3000 },
    { category: "Смарт-годинники", name: "Realme Watch 4", price: 3600 },
    { category: "Смарт-годинники", name: "OnePlus Watch 2", price: 11000 },

    { category: "Телефони", name: "Apple iPhone 13", price: 38000 },
    { category: "Телефони", name: "Apple iPhone 14", price: 42000 },
    { category: "Телефони", name: "Apple iPhone 15", price: 52000 },
    { category: "Телефони", name: "Samsung Galaxy S22", price: 36000 },
    { category: "Телефони", name: "Samsung Galaxy A54", price: 18000 },
    { category: "Телефони", name: "Xiaomi Redmi Note 12", price: 12000 },
    { category: "Телефони", name: "Xiaomi 13T Pro", price: 26000 },
    { category: "Телефони", name: "Realme 11 Pro", price: 17000 },
    { category: "Телефони", name: "Google Pixel 7", price: 30000 },
    { category: "Телефони", name: "Nothing Phone (2)", price: 28000 },
    { category: "Телефони", name: "Samsung Galaxy S23", price: 39000 },
    { category: "Телефони", name: "Xiaomi Redmi 13C", price: 9000 },
    { category: "Телефони", name: "OnePlus Nord 3", price: 20000 },
    { category: "Телефони", name: "Huawei P60 Pro", price: 34000 },
    { category: "Телефони", name: "Motorola Edge 40", price: 21000 }
  ];    

const Order = [
    { id: 1, clientId: 3, date: new Date("2024-01-12"), status: "Обробка", address: "м. Львів, вул. Зелена, 15", deliveryStatus: "Готується" },
    { id: 2, clientId: 5, date: new Date("2024-01-20"), status: "Доставка", address: "м. Київ, вул. Богдана Хмельницького, 22", deliveryStatus: "В дорозі" },
    { id: 3, clientId: 7, date: new Date("2024-02-05"), status: "Завершено", address: "м. Рівне, вул. Соборна, 81", deliveryStatus: "Доставлено" },
    { id: 4, clientId: 8, date: new Date("2024-02-19"), status: "Обробка", address: "м. Луцьк, вул. Дубнівська, 40", deliveryStatus: "Готується" },
    { id: 5, clientId: 10, date: new Date("2024-03-01"), status: "Доставка", address: "м. Полтава, вул. Грушевського, 11", deliveryStatus: "В дорозі" },

    { id: 6, clientId: 12, date: new Date("2024-03-10"), status: "Завершено", address: "м. Одеса, вул. Пушкінська, 8", deliveryStatus: "Доставлено" },
    { id: 7, clientId: 13, date: new Date("2024-03-28"), status: "Обробка", address: "м. Івано-Франківськ, вул. Коновальця, 34", deliveryStatus: "Готується" },
    { id: 8, clientId: 15, date: new Date("2024-04-04"), status: "Доставка", address: "м. Харків, вул. Наукова, 19", deliveryStatus: "В дорозі" },
    { id: 9, clientId: 17, date: new Date("2024-04-18"), status: "Завершено", address: "м. Житомир, вул. Київська, 88", deliveryStatus: "Доставлено" },
    { id: 10, clientId: 18, date: new Date("2024-04-29"), status: "Обробка", address: "м. Чернігів, вул. Шевченка, 25", deliveryStatus: "Готується" },

    { id: 11, clientId: 20, date: new Date("2024-05-03"), status: "Доставка", address: "м. Ужгород, вул. Минайська, 77", deliveryStatus: "В дорозі" },
    { id: 12, clientId: 21, date: new Date("2024-05-15"), status: "Завершено", address: "м. Львів, вул. Кульпарківська, 106", deliveryStatus: "Доставлено" },
    { id: 13, clientId: 23, date: new Date("2024-05-28"), status: "Обробка", address: "м. Київ, вул. Лесі Українки, 12", deliveryStatus: "Готується" },
    { id: 14, clientId: 25, date: new Date("2024-06-09"), status: "Доставка", address: "м. Одеса, вул. Армейська, 3", deliveryStatus: "В дорозі" },
    { id: 15, clientId: 26, date: new Date("2024-06-17"), status: "Завершено", address: "м. Рівне, вул. Чорновола, 56", deliveryStatus: "Доставлено" },

    { id: 16, clientId: 28, date: new Date("2024-06-30"), status: "Обробка", address: "м. Чернівці, вул. Героїв Майдану, 44", deliveryStatus: "Готується" },
    { id: 17, clientId: 30, date: new Date("2024-07-11"), status: "Доставка", address: "м. Тернопіль, вул. Живова, 20", deliveryStatus: "В дорозі" },
    { id: 18, clientId: 32, date: new Date("2024-07-25"), status: "Завершено", address: "м. Дніпро, вул. Калинова, 7", deliveryStatus: "Доставлено" },
    { id: 19, clientId: 34, date: new Date("2024-08-02"), status: "Обробка", address: "м. Харків, вул. Мироносицька, 15", deliveryStatus: "Готується" },
    { id: 20, clientId: 35, date: new Date("2024-08-16"), status: "Доставка", address: "м. Київ, вул. Антоновича, 51", deliveryStatus: "В дорозі" },
  
    { id: 21, clientId: 37, date: new Date("2024-08-28"), status: "Завершено", address: "м. Львів, вул. Пасічна, 102", deliveryStatus: "Доставлено" },
    { id: 22, clientId: 38, date: new Date("2024-09-05"), status: "Обробка", address: "м. Рівне, вул. Млинівська, 24", deliveryStatus: "Готується" },
    { id: 23, clientId: 40, date: new Date("2024-09-19"), status: "Доставка", address: "м. Черкаси, вул. Гагаріна, 14", deliveryStatus: "В дорозі" },
    { id: 24, clientId: 41, date: new Date("2024-10-02"), status: "Завершено", address: "м. Харків, вул. Пушкінська, 67", deliveryStatus: "Доставлено" },
    { id: 25, clientId: 43, date: new Date("2024-10-14"), status: "Обробка", address: "м. Київ, вул. Саксаганського, 112", deliveryStatus: "Готується" },

    { id: 26, clientId: 44, date: new Date("2024-10-29"), status: "Доставка", address: "м. Івано-Франківськ, вул. Незалежності, 17", deliveryStatus: "В дорозі" },
    { id: 27, clientId: 46, date: new Date("2024-11-08"), status: "Завершено", address: "м. Чернівці, вул. Героїв Майдану, 9", deliveryStatus: "Доставлено" },
    { id: 28, clientId: 48, date: new Date("2024-11-22"), status: "Обробка", address: "м. Дніпро, вул. Поля, 33", deliveryStatus: "Готується" },
    { id: 29, clientId: 49, date: new Date("2024-12-03"), status: "Доставка", address: "м. Одеса, вул. Академіка Філатова, 55", deliveryStatus: "В дорозі" },
    { id: 30, clientId: 51, date: new Date("2024-12-18"), status: "Завершено", address: "м. Луцьк, вул. Винниченка, 10", deliveryStatus: "Доставлено" },

    { id: 31, clientId: 52, date: new Date("2025-01-09"), status: "Обробка", address: "м. Полтава, вул. Садова, 61", deliveryStatus: "Готується" },
    { id: 32, clientId: 54, date: new Date("2025-01-23"), status: "Доставка", address: "м. Житомир, вул. Бердичівська, 87", deliveryStatus: "В дорозі" },
    { id: 33, clientId: 55, date: new Date("2025-02-02"), status: "Завершено", address: "м. Львів, вул. Шевченка, 210", deliveryStatus: "Доставлено" },
    { id: 34, clientId: 57, date: new Date("2025-02-18"), status: "Обробка", address: "м. Київ, вул. Володимирська, 14", deliveryStatus: "Готується" },
    { id: 35, clientId: 58, date: new Date("2025-03-01"), status: "Доставка", address: "м. Черкаси, вул. Благовісна, 25", deliveryStatus: "В дорозі" },

    { id: 36, clientId: 60, date: new Date("2025-03-15"), status: "Завершено", address: "м. Харків, вул. Полтавський шлях, 88", deliveryStatus: "Доставлено" },
    { id: 37, clientId: 62, date: new Date("2025-03-28"), status: "Обробка", address: "м. Тернопіль, вул. Руська, 31", deliveryStatus: "Готується" },
    { id: 38, clientId: 63, date: new Date("2025-04-10"), status: "Доставка", address: "м. Київ, вул. Драгоманова, 7", deliveryStatus: "В дорозі" },
    { id: 39, clientId: 65, date: new Date("2025-04-22"), status: "Завершено", address: "м. Одеса, вул. Успенська, 5", deliveryStatus: "Доставлено" },
    { id: 40, clientId: 66, date: new Date("2025-05-06"), status: "Обробка", address: "м. Львів, вул. Мазепи, 45", deliveryStatus: "Готується" },
     
    { id: 41, clientId: 68, date: new Date("2025-05-18"), status: "Доставка", address: "м. Чернівці, вул. Головна, 219", deliveryStatus: "В дорозі" },
    { id: 42, clientId: 69, date: new Date("2025-05-29"), status: "Завершено", address: "м. Київ, вул. Вишгородська, 10", deliveryStatus: "Доставлено" },
    { id: 43, clientId: 71, date: new Date("2025-06-07"), status: "Обробка", address: "м. Дніпро, вул. Грушевського, 77", deliveryStatus: "Готується" },
    { id: 44, clientId: 72, date: new Date("2025-06-19"), status: "Доставка", address: "м. Харків, вул. Сумська, 47", deliveryStatus: "В дорозі" },
    { id: 45, clientId: 74, date: new Date("2025-07-01"), status: "Завершено", address: "м. Одеса, вул. Пироговська, 12", deliveryStatus: "Доставлено" },

    { id: 46, clientId: 75, date: new Date("2025-07-11"), status: "Обробка", address: "м. Львів, вул. Богдана Хмельницького, 95", deliveryStatus: "Готується" },
    { id: 47, clientId: 77, date: new Date("2025-07-24"), status: "Доставка", address: "м. Луцьк, вул. Привокзальна, 32", deliveryStatus: "В дорозі" },
    { id: 48, clientId: 78, date: new Date("2025-08-05"), status: "Завершено", address: "м. Рівне, вул. Княгині Ольги, 17", deliveryStatus: "Доставлено" },
    { id: 49, clientId: 80, date: new Date("2025-08-16"), status: "Обробка", address: "м. Черкаси, вул. Смілянська, 140", deliveryStatus: "Готується" },
    { id: 50, clientId: 81, date: new Date("2025-08-27"), status: "Доставка", address: "м. Суми, вул. Харківська, 22", deliveryStatus: "В дорозі" },

    { id: 51, clientId: 83, date: new Date("2025-09-08"), status: "Завершено", address: "м. Тернопіль, вул. Коперника, 5", deliveryStatus: "Доставлено" },
    { id: 52, clientId: 84, date: new Date("2025-09-20"), status: "Обробка", address: "м. Львів, вул. Наукова, 55", deliveryStatus: "Готується" },
    { id: 53, clientId: 86, date: new Date("2025-09-30"), status: "Доставка", address: "м. Київ, вул. Дніпровська набережна, 3", deliveryStatus: "В дорозі" },
    { id: 54, clientId: 87, date: new Date("2025-10-12"), status: "Завершено", address: "м. Хмельницький, вул. Зарічанська, 42", deliveryStatus: "Доставлено" },
    { id: 55, clientId: 89, date: new Date("2025-10-25"), status: "Обробка", address: "м. Одеса, вул. Канатна, 99", deliveryStatus: "Готується" },

    { id: 56, clientId: 90, date: new Date("2025-11-07"), status: "Доставка", address: "м. Ужгород, вул. Собранецька, 15", deliveryStatus: "В дорозі" },
    { id: 57, clientId: 92, date: new Date("2025-11-19"), status: "Завершено", address: "м. Вінниця, вул. Келецька, 61", deliveryStatus: "Доставлено" },
    { id: 58, clientId: 93, date: new Date("2025-11-30"), status: "Обробка", address: "м. Львів, вул. Драгоманова, 8", deliveryStatus: "Готується" },
    { id: 59, clientId: 95, date: new Date("2025-12-10"), status: "Доставка", address: "м. Івано-Франківськ, вул. Хоткевича, 40", deliveryStatus: "В дорозі" },
    { id: 60, clientId: 97, date: new Date("2025-12-22"), status: "Завершено", address: "м. Київ, вул. Хрещатик, 17", deliveryStatus: "Доставлено" },

    { id: 61, clientId: 98, date: new Date("2025-12-28"), status: "Обробка", address: "м. Одеса, вул. Рішельєвська, 13", deliveryStatus: "Готується" },
    { id: 62, clientId: 99, date: new Date("2025-12-30"), status: "Доставка", address: "м. Чернігів, вул. Рокоссовського, 22", deliveryStatus: "В дорозі" },
    { id: 63, clientId: 100, date: new Date("2025-12-31"), status: "Завершено", address: "м. Херсон, вул. Перекопська, 55", deliveryStatus: "Доставлено" },

    { id: 64, clientId: 4, date: new Date("2024-01-17"), status: "Обробка", address: "м. Львів, вул. Любінська, 102", deliveryStatus: "Готується" },
    { id: 65, clientId: 11, date: new Date("2024-02-11"), status: "Доставка", address: "м. Київ, вул. Гоголівська, 29", deliveryStatus: "В дорозі" },
    { id: 66, clientId: 14, date: new Date("2024-03-22"), status: "Завершено", address: "м. Рівне, вул. Дубенська, 5", deliveryStatus: "Доставлено" },

    { id: 67, clientId: 19, date: new Date("2024-04-06"), status: "Обробка", address: "м. Харків, вул. Героїв Праці, 33", deliveryStatus: "Готується" },
    { id: 68, clientId: 22, date: new Date("2024-05-15"), status: "Доставка", address: "м. Одеса, вул. Тираспольська, 18", deliveryStatus: "В дорозі" },
    { id: 69, clientId: 29, date: new Date("2024-06-09"), status: "Завершено", address: "м. Ужгород, вул. Капушанська, 48", deliveryStatus: "Доставлено" },

    { id: 70, clientId: 33, date: new Date("2024-07-12"), status: "Обробка", address: "м. Луцьк, вул. Рівненська, 87", deliveryStatus: "Готується" },
    { id: 71, clientId: 36, date: new Date("2024-08-03"), status: "Доставка", address: "м. Київ, вул. Срібнокільська, 1", deliveryStatus: "В дорозі" },
    { id: 72, clientId: 42, date: new Date("2024-09-14"), status: "Завершено", address: "м. Полтава, вул. Маршала Бірюзова, 19", deliveryStatus: "Доставлено" },

    { id: 73, clientId: 45, date: new Date("2024-10-05"), status: "Обробка", address: "м. Тернопіль, вул. Текстильна, 35", deliveryStatus: "Готується" },
    { id: 74, clientId: 47, date: new Date("2024-11-08"), status: "Доставка", address: "м. Харків, вул. Ахсарова, 7", deliveryStatus: "В дорозі" },
    { id: 75, clientId: 50, date: new Date("2024-12-01"), status: "Завершено", address: "м. Львів, вул. Панаса Мирного, 20", deliveryStatus: "Доставлено" },

    { id: 76, clientId: 53, date: new Date("2025-01-14"), status: "Обробка", address: "м. Київ, вул. Березняківська, 17", deliveryStatus: "Готується" },
    { id: 77, clientId: 56, date: new Date("2025-02-09"), status: "Доставка", address: "м. Житомир, вул. Домбровського, 9", deliveryStatus: "В дорозі" },
    { id: 78, clientId: 59, date: new Date("2025-03-03"), status: "Завершено", address: "м. Дніпро, вул. Робоча, 77", deliveryStatus: "Доставлено" },

    { id: 79, clientId: 64, date: new Date("2025-03-26"), status: "Обробка", address: "м. Київ, вул. Милославська, 33", deliveryStatus: "Готується" },
    { id: 80, clientId: 67, date: new Date("2025-04-18"), status: "Доставка", address: "м. Одеса, вул. Львівська, 5", deliveryStatus: "В дорозі" },
    { id: 81, clientId: 70, date: new Date("2025-05-11"), status: "Завершено", address: "м. Івано-Франківськ, вул. Хоткевича, 22", deliveryStatus: "Доставлено" },

    { id: 82, clientId: 73, date: new Date("2025-06-15"), status: "Обробка", address: "м. Хмельницький, вул. Інститутська, 16", deliveryStatus: "Готується" },
    { id: 83, clientId: 76, date: new Date("2025-07-02"), status: "Доставка", address: "м. Луцьк, вул. Січова, 14", deliveryStatus: "В дорозі" },
    { id: 84, clientId: 79, date: new Date("2025-07-27"), status: "Завершено", address: "м. Черкаси, вул. Байди Вишневецького, 12", deliveryStatus: "Доставлено" },

    { id: 85, clientId: 82, date: new Date("2025-08-11"), status: "Обробка", address: "м. Київ, вул. Регенераторна, 4", deliveryStatus: "Готується" },
    { id: 86, clientId: 84, date: new Date("2025-08-28"), status: "Доставка", address: "м. Львів, вул. Миколайчука, 38", deliveryStatus: "В дорозі" },
    { id: 87, clientId: 86, date: new Date("2025-09-14"), status: "Завершено", address: "м. Одеса, вул. Новощіпний ряд, 31", deliveryStatus: "Доставлено" },

    { id: 88, clientId: 88, date: new Date("2025-10-01"), status: "Обробка", address: "м. Дніпро, вул. Каруни, 40", deliveryStatus: "Готується" },
    { id: 89, clientId: 91, date: new Date("2025-10-24"), status: "Доставка", address: "м. Київ, вул. Єреванська, 25", deliveryStatus: "В дорозі" },
    { id: 90, clientId: 94, date: new Date("2025-11-09"), status: "Завершено", address: "м. Херсон, вул. Белінського, 8", deliveryStatus: "Доставлено" },
  ];  

const OrderDetail = [
    { orderId: 1, productId: 1, quantity: 1 },
    { orderId: 1, productId: 42, quantity: 1 },
    { orderId: 2, productId: 20, quantity: 1 },
    { orderId: 2, productId: 55, quantity: 1 },
    { orderId: 3, productId: 68, quantity: 1 },
    { orderId: 4, productId: 30, quantity: 1 },
    { orderId: 4, productId: 49, quantity: 1 },
    { orderId: 5, productId: 23, quantity: 1 },
    { orderId: 6, productId: 10, quantity: 1 },
    { orderId: 6, productId: 43, quantity: 1 },
    { orderId: 7, productId: 57, quantity: 1 },
    { orderId: 8, productId: 6, quantity: 1 },
    { orderId: 8, productId: 44, quantity: 1 },
    { orderId: 9, productId: 25, quantity: 1 },
    { orderId: 9, productId: 52, quantity: 1 },
    { orderId: 10, productId: 32, quantity: 1 },
    { orderId: 11, productId: 70, quantity: 1 },
    { orderId: 12, productId: 5, quantity: 1 },
    { orderId: 12, productId: 41, quantity: 1 },
    { orderId: 13, productId: 61, quantity: 1 },
    { orderId: 14, productId: 18, quantity: 1 },
    { orderId: 14, productId: 58, quantity: 1 },
    { orderId: 14, productId: 75, quantity: 1 },
    { orderId: 15, productId: 44, quantity: 1 },
    { orderId: 15, productId: 42, quantity: 1 },
    { orderId: 16, productId: 7, quantity: 1 },
    { orderId: 16, productId: 43, quantity: 2 },
    { orderId: 17, productId: 21, quantity: 1 },
    { orderId: 17, productId: 55, quantity: 1 },
    { orderId: 18, productId: 68, quantity: 2 },
    { orderId: 19, productId: 11, quantity: 1 },
    { orderId: 19, productId: 49, quantity: 1 },
    { orderId: 20, productId: 25, quantity: 1 },
    { orderId: 20, productId: 57, quantity: 2 },
    { orderId: 21, productId: 3, quantity: 1 },
    { orderId: 21, productId: 44, quantity: 1 },
    { orderId: 22, productId: 32, quantity: 1 },
    { orderId: 23, productId: 20, quantity: 1 },
    { orderId: 23, productId: 73, quantity: 1 },
    { orderId: 24, productId: 6, quantity: 1 },
    { orderId: 24, productId: 41, quantity: 1 },
    { orderId: 25, productId: 18, quantity: 1 },
    { orderId: 25, productId: 52, quantity: 2 },
    { orderId: 26, productId: 30, quantity: 1 },
    { orderId: 27, productId: 10, quantity: 1 },
    { orderId: 27, productId: 68, quantity: 1 },
    { orderId: 28, productId: 14, quantity: 1 },
    { orderId: 28, productId: 44, quantity: 1 },
    { orderId: 29, productId: 22, quantity: 2 },
    { orderId: 30, productId: 71, quantity: 1 },
    { orderId: 30, productId: 55, quantity: 1 },
    { orderId: 31, productId: 2, quantity: 1 },
    { orderId: 31, productId: 41, quantity: 1 },
    { orderId: 32, productId: 19, quantity: 1 },
    { orderId: 33, productId: 32, quantity: 1 },
    { orderId: 33, productId: 49, quantity: 1 },
    { orderId: 34, productId: 23, quantity: 2 },
    { orderId: 35, productId: 70, quantity: 1 },
    { orderId: 36, productId: 5, quantity: 1 },
    { orderId: 36, productId: 42, quantity: 1 },
    { orderId: 37, productId: 14, quantity: 1 },
    { orderId: 37, productId: 56, quantity: 2 },
    { orderId: 38, productId: 18, quantity: 1 },
    { orderId: 38, productId: 58, quantity: 1 },
    { orderId: 39, productId: 6, quantity: 1 },
    { orderId: 39, productId: 44, quantity: 1 },
    { orderId: 40, productId: 28, quantity: 1 },
    { orderId: 41, productId: 11, quantity: 1 },
    { orderId: 41, productId: 43, quantity: 2 },
    { orderId: 42, productId: 33, quantity: 1 },
    { orderId: 43, productId: 3, quantity: 1 },
    { orderId: 43, productId: 57, quantity: 1 },
    { orderId: 44, productId: 21, quantity: 1 },
    { orderId: 44, productId: 55, quantity: 1 },
    { orderId: 45, productId: 10, quantity: 1 },
    { orderId: 45, productId: 41, quantity: 1 },
    { orderId: 46, productId: 7, quantity: 1 },
    { orderId: 46, productId: 42, quantity: 1 },
    { orderId: 47, productId: 20, quantity: 1 },
    { orderId: 47, productId: 55, quantity: 2 },
    { orderId: 48, productId: 68, quantity: 1 },
    { orderId: 49, productId: 30, quantity: 1 },
    { orderId: 49, productId: 49, quantity: 1 },
    { orderId: 50, productId: 23, quantity: 2 },
    { orderId: 51, productId: 10, quantity: 1 },
    { orderId: 51, productId: 43, quantity: 1 },
    { orderId: 52, productId: 57, quantity: 1 },
    { orderId: 53, productId: 6, quantity: 1 },
    { orderId: 53, productId: 44, quantity: 1 },
    { orderId: 54, productId: 25, quantity: 1 },
    { orderId: 54, productId: 52, quantity: 2 },
    { orderId: 55, productId: 32, quantity: 1 },
    { orderId: 56, productId: 70, quantity: 1 },
    { orderId: 57, productId: 5, quantity: 1 },
    { orderId: 57, productId: 41, quantity: 1 },
    { orderId: 58, productId: 14, quantity: 1 },
    { orderId: 58, productId: 58, quantity: 1 },
    { orderId: 59, productId: 11, quantity: 1 },
    { orderId: 59, productId: 49, quantity: 1 },
    { orderId: 60, productId: 33, quantity: 1 },
    { orderId: 60, productId: 73, quantity: 1 },
    { orderId: 61, productId: 1, quantity: 1 },
    { orderId: 61, productId: 42, quantity: 2 },
    { orderId: 62, productId: 20, quantity: 1 },
    { orderId: 62, productId: 58, quantity: 1 },
    { orderId: 63, productId: 68, quantity: 1 },
    { orderId: 64, productId: 30, quantity: 1 },
    { orderId: 64, productId: 49, quantity: 1 },
    { orderId: 65, productId: 23, quantity: 2 },
    { orderId: 66, productId: 10, quantity: 1 },
    { orderId: 66, productId: 41, quantity: 1 },
    { orderId: 67, productId: 57, quantity: 1 },
    { orderId: 68, productId: 14, quantity: 1 },
    { orderId: 68, productId: 56, quantity: 2 },
    { orderId: 69, productId: 18, quantity: 1 },
    { orderId: 69, productId: 75, quantity: 1 },
    { orderId: 70, productId: 6, quantity: 1 },
    { orderId: 70, productId: 44, quantity: 1 },
    { orderId: 71, productId: 25, quantity: 1 },
    { orderId: 72, productId: 32, quantity: 1 },
    { orderId: 72, productId: 49, quantity: 1 },
    { orderId: 73, productId: 70, quantity: 1 },
    { orderId: 74, productId: 5, quantity: 1 },
    { orderId: 74, productId: 42, quantity: 1 },
    { orderId: 75, productId: 14, quantity: 1 },
    { orderId: 75, productId: 55, quantity: 1 },
    { orderId: 76, productId: 20, quantity: 2 },
    { orderId: 77, productId: 68, quantity: 1 },
    { orderId: 78, productId: 30, quantity: 1 },
    { orderId: 78, productId: 49, quantity: 1 },
    { orderId: 79, productId: 23, quantity: 1 },
    { orderId: 79, productId: 73, quantity: 1 },
    { orderId: 80, productId: 10, quantity: 1 },
    { orderId: 80, productId: 43, quantity: 1 },
    { orderId: 81, productId: 57, quantity: 1 },
    { orderId: 82, productId: 18, quantity: 1 },
    { orderId: 82, productId: 56, quantity: 1 },
    { orderId: 83, productId: 6, quantity: 1 },
    { orderId: 83, productId: 44, quantity: 1 },
    { orderId: 84, productId: 25, quantity: 2 },
    { orderId: 85, productId: 32, quantity: 1 },
    { orderId: 86, productId: 70, quantity: 1 },
    { orderId: 87, productId: 5, quantity: 1 },
    { orderId: 87, productId: 41, quantity: 1 },
    { orderId: 88, productId: 14, quantity: 1 },
    { orderId: 88, productId: 58, quantity: 1 },
    { orderId: 89, productId: 18, quantity: 1 },
    { orderId: 89, productId: 75, quantity: 1 },
    { orderId: 90, productId: 10, quantity: 1 },
    { orderId: 90, productId: 43, quantity: 1 },
]; 

const Payment = [
    { orderId: 1, method: "Карта",   amount: 50000 },
    { orderId: 2, method: "Готівка", amount: 42000 },
    { orderId: 3, method: "Карта",   amount: 21000 },
    { orderId: 4, method: "Готівка", amount: 90000 },
    { orderId: 5, method: "Карта",   amount: 28000 },
    { orderId: 6, method: "Готівка", amount: 50000 },
    { orderId: 7, method: "Карта",   amount: 15000 },
    { orderId: 8, method: "Готівка", amount: 135000 },
    { orderId: 9, method: "Карта",   amount: 13500 },
    { orderId: 10, method: "Готівка", amount: 12000 },

    { orderId: 11, method: "Карта",   amount: 38000 },
    { orderId: 12, method: "Готівка", amount: 69000 },
    { orderId: 13, method: "Карта",   amount: 42000 },
    { orderId: 14, method: "Готівка", amount: 112000 },
    { orderId: 15, method: "Карта",   amount: 108000 },
    { orderId: 16, method: "Готівка", amount: 130000 },
    { orderId: 17, method: "Карта",   amount: 30000 },
    { orderId: 18, method: "Готівка", amount: 42000 },
    { orderId: 19, method: "Карта",   amount: 167000 },
    { orderId: 20, method: "Готівка", amount: 41000 },

    { orderId: 21, method: "Карта",   amount: 125000 },
    { orderId: 22, method: "Готівка", amount: 12000 },
    { orderId: 23, method: "Карта",   amount: 52000 },
    { orderId: 24, method: "Готівка", amount: 83000 },
    { orderId: 25, method: "Карта",   amount: 65000 },
    { orderId: 26, method: "Готівка", amount: 13000 },
    { orderId: 27, method: "Карта",   amount: 47000 },
    { orderId: 28, method: "Готівка", amount: 119000 },
    { orderId: 29, method: "Карта",   amount: 56000 },
    { orderId: 30, method: "Готівка", amount: 48000 },

    { orderId: 31, method: "Карта",   amount: 45000 },
    { orderId: 32, method: "Готівка", amount: 32000 },
    { orderId: 33, method: "Карта",   amount: 75000 },
    { orderId: 34, method: "Готівка", amount: 26000 },
    { orderId: 35, method: "Карта",   amount: 97000 },
    { orderId: 36, method: "Готівка", amount: 52000 },
    { orderId: 37, method: "Карта",   amount: 31000 },
    { orderId: 38, method: "Готівка", amount: 88000 },
    { orderId: 39, method: "Карта",   amount: 60000 },
    { orderId: 40, method: "Готівка", amount: 43000 },

    { orderId: 41, method: "Карта",   amount: 39000 },
    { orderId: 42, method: "Готівка", amount: 27000 },
    { orderId: 43, method: "Карта",   amount: 33000 },
    { orderId: 44, method: "Готівка", amount: 92000 },
    { orderId: 45, method: "Карта",   amount: 14000 },
    { orderId: 46, method: "Готівка", amount: 36000 },
    { orderId: 47, method: "Карта",   amount: 29500 },
    { orderId: 48, method: "Готівка", amount: 41000 },
    { orderId: 49, method: "Карта",   amount: 51000 },
    { orderId: 50, method: "Готівка", amount: 23000 },

    { orderId: 51, method: "Карта",   amount: 78000 },
    { orderId: 52, method: "Готівка", amount: 54000 },
    { orderId: 53, method: "Карта",   amount: 36000 },
    { orderId: 54, method: "Готівка", amount: 66000 },
    { orderId: 55, method: "Карта",   amount: 25000 },
    { orderId: 56, method: "Готівка", amount: 44000 },
    { orderId: 57, method: "Карта",   amount: 59000 },
    { orderId: 58, method: "Готівка", amount: 30500 },
    { orderId: 59, method: "Карта",   amount: 47000 },
    { orderId: 60, method: "Готівка", amount: 51500 },

    { orderId: 61, method: "Карта",   amount: 80000 },
    { orderId: 62, method: "Готівка", amount: 92000 },
    { orderId: 63, method: "Карта",   amount: 38500 },
    { orderId: 64, method: "Готівка", amount: 27000 },
    { orderId: 65, method: "Карта",   amount: 73000 },
    { orderId: 66, method: "Готівка", amount: 64000 },
    { orderId: 67, method: "Карта",   amount: 41000 },
    { orderId: 68, method: "Готівка", amount: 58000 },
    { orderId: 69, method: "Карта",   amount: 69500 },
    { orderId: 70, method: "Готівка", amount: 52000 }
  ];   

async function seed() {
  await sequelize.sync({ force: true });

  await Client.bulkCreate(clients);
  await Product.bulkCreate(products);
  await Order.bulkCreate(orders);
  await OrderDetail.bulkCreate(orderDetails);
  await Payment.bulkCreate(payments);

  process.exit(0);
}

seed();
